// player config
export const PLAYER_LIVES = 3;
export const PLAYER_HEALTH = 3;
export const PLAYER_BULLET_SPEED = 300;
export const PLAYER_BULLET_INTERVAL = 300;
export const PLAYER_BULLET_LIFESPAN = 3;
export const PLAYER_BULLET_MAX_COUNT = 10;
export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;

// enemy fighter config
export const ENEMY_FIGHTER_SCORE = 0;
export const ENEMY_FIGHTER_HEALTH = 2;
export const ENEMY_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 12;
export const ENEMY_FIGHTER_BULLET_SPEED = -280;
export const ENEMY_FIGHTER_BULLET_INTERVAL = 2000;
export const ENEMY_FIGHTER_BULLET_LIFESPAN = 3;
export const ENEMY_FIGHTER_BULLET_MAX_COUNT = 10;
export const ENEMY_FIGHTER_GROUP_SPAWN_INTERVAL = 3000;
export const ENEMY_FIGHTER_GROUP_SPAWN_START = 3000;

// enemy rock config
export const ENEMY_ROCK_SCORE = 0;
export const ENEMY_ROCK_HEALTH = 10;
export const ENEMY_ROCK_MOVEMENT_VERTICAL_VELOCITY = 12;
export const ENEMY_ROCK_GROUP_SPAWN_INTERVAL = 10000;
export const ENEMY_ROCK_GROUP_SPAWN_START = 4000;

// item meat config
export const ITEM_MEAT_SCORE = 2;
export const ITEM_MEAT_HEALTH = 10;
export const ITEM_MEAT_MOVEMENT_VERTICAL_VELOCITY = 5;
export const ITEM_MEAT_GROUP_SPAWN_INTERVAL = 6000;
export const ITEM_MEAT_GROUP_SPAWN_START = 2000;

// enemy scout config
export const ENEMY_SCOUT_SCORE = 0;
export const ENEMY_SCOUT_HEALTH = 2;
export const ENEMY_SCOUT_MOVEMENT_MAX_X = 40;
export const ENEMY_SCOUT_MOVEMENT_VERTICAL_VELOCITY = 10;
export const ENEMY_SCOUT_MOVEMENT_HORIZONTAL_VELOCITY = 9;
export const ENEMY_SCOUT_GROUP_SPAWN_INTERVAL = 2000;
export const ENEMY_SCOUT_GROUP_SPAWN_START = 1000;

// item prisoner config
export const ITEM_PRISONER_SCORE = 5;
export const ITEM_PRISONER_HEALTH = 2;
export const ITEM_PRISONER_MOVEMENT_MAX_X = 40;
export const ITEM_PRISONER_MOVEMENT_VERTICAL_VELOCITY = 15;
export const ITEM_PRISONER_MOVEMENT_HORIZONTAL_VELOCITY = 9;
export const ITEM_PRISONER_GROUP_SPAWN_INTERVAL = 10000;
export const ITEM_PRISONER_GROUP_SPAWN_START = 5000;

// component config
export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 200;
export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 200;
